version: "2"
linters:
  default: all
  disable:
    - err113              # makes it impossible to use errors.New() in tests
    - exhaustruct         # makes partial struct initialization impossible
    - funlen              # function length is subjective, not objective
    - gochecknoglobals    # there are legitimate uses for global variables
    - godot               # not all comments should end with a period
    - lll                 # long lines (> col 120)
    - nlreturn            # another whitespace nazi
    - thelper             # makes scenario exec(testing.T) test cases impossible
    - paralleltest        # parallel tests are not always appropriate
    - varnamelen          # variable names must be at least 3 characters long
    - wsl                 # absolute PoS whitespace nazi

    # not supported when go.mod Go version is <1.22
    - copyloopvar
    - intrange

  settings:
    depguard:
      rules:
        tests:
          files:
            - $test
          list-mode: lax
          allow: ["*"]

    godox:
      keywords:
        - TODO

    ireturn:
      reject:
        - empty           # should never return interface{}

    revive:
      rules:
        - name: package-comments
          disabled: true

    staticcheck:
      checks:
        - -QF1008         # Disable "could remove embedded field <name> from selector"
